// ==============================================================================
// CBA9FITNESS - SUPABASE EDGE FUNCTION: notify-admin
// ==============================================================================
// Deploy this function with: supabase functions deploy notify-admin
// Set Secret (e.g. Resend API Key): supabase secrets set RESEND_API_KEY=re_xxxxxx
// ==============================================================================

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  // Handle CORS Preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { adminEmail, subject, data } = await req.json();

    const targetEmail = adminEmail || Deno.env.get("ADMIN_EMAIL") || "cba9fitness@gmail.com";
    const resendApiKey = Deno.env.get("RESEND_API_KEY");

    // Format Data into HTML Table
    let rowsHtml = "";
    for (const [key, value] of Object.entries(data || {})) {
      rowsHtml += `
        <tr style="border-bottom: 1px solid #1E293B;">
          <td style="padding: 10px 14px; font-weight: bold; color: #94A3B8; width: 35%;">${key}</td>
          <td style="padding: 10px 14px; color: #F8FAFC;">${value}</td>
        </tr>
      `;
    }

    const emailHtml = `
      <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #070B12; color: #F8FAFC; border: 1px solid #1E293B; border-radius: 8px; overflow: hidden;">
        <div style="background: #0E1624; padding: 20px 24px; border-bottom: 2px solid #3B82F6;">
          <h2 style="margin: 0; color: #FFFFFF; font-size: 20px; letter-spacing: 1px;">⚡ CBA9FITNESS ALERT</h2>
          <p style="margin: 4px 0 0; color: #60A5FA; font-size: 14px;">${subject}</p>
        </div>
        <div style="padding: 24px;">
          <table style="width: 100%; border-collapse: collapse; background: #0A0F1D; border-radius: 6px; overflow: hidden;">
            ${rowsHtml}
          </table>
          <p style="margin-top: 24px; font-size: 12px; color: #64748B; text-align: center;">
            This automated alert was generated by the CBA9Fitness Supabase Backend.
          </p>
        </div>
      </div>
    `;

    // If Resend API Key is provided, dispatch email via Resend API
    if (resendApiKey) {
      const res = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${resendApiKey}`,
        },
        body: JSON.stringify({
          from: "CBA9Fitness Notifications <notifications@resend.dev>",
          to: [targetEmail],
          subject: subject || "New Notification from CBA9Fitness",
          html: emailHtml,
        }),
      });

      const resData = await res.json();
      return new Response(JSON.stringify({ success: true, resData }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      });
    }

    // Fallback response if no email provider key set yet (logs payload)
    console.log(`[notify-admin] Target: ${targetEmail} | Data:`, data);
    return new Response(
      JSON.stringify({ 
        success: true, 
        message: `Notification logged for ${targetEmail}. Configure RESEND_API_KEY to send live emails.` 
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 400,
    });
  }
});
